"""
部门/模块 中英文路径映射表

目录命名规范: 英文小写 kebab-case
数据库显示名: 保持中文不变
"""

# 部门映射（中文名 → 英文路径名，与前端 constants.js DEPT_OPTIONS 保持一致）
DEPT_TO_PATH = {
    "数智财务组": "fin-tech",
    "免疫规划组": "immunization",
    "电子档案组": "e-archive",
    "数字化支撑组": "digital-support",
    "共享业务部": "shared-business",
    "质量测评部": "quality",
    "产品设计部": "product-design",
    "业务研发部": "business-dev",
    "基础架构部": "infrastructure",
    "基础保障部": "basic-support",
    "溯采产研部": "sourcing",
    "政采研发": "gov-procurement-dev",
    "惠采业务中心": "benefit-procurement",
    "惠采研发中心": "benefit-procurement-dev",
    "数据管理部": "data-management",
    "AI研发": "ai-dev",
    "行业采购": "industry-procurement",
    "政采交付": "gov-procurement-delivery",
    "体验运营": "ux-operations",
    "政采质量保障": "gov-procurement-qa",
}
PATH_TO_DEPT = {v: k for k, v in DEPT_TO_PATH.items()}

# 子模块映射
SUBMODULE_TO_PATH = {
    "AI应用": "ai-ying-yong",
    "AI接口服务": "ai-jie-kou-fu-wu",
    "API管理系统": "api-guan-li-xi-tong",
    "API网关": "api-wang-guan",
    "CA管理系统": "ca-guan-li-xi-tong",
    "CRM": "crm",
    "IData": "idata",
    "IM": "im",
    "KA-专家抽取": "ka--zhuan-jia-chou-qu",
    "KA-共享服务": "ka--gong-xiang-fu-wu",
    "KA-合同履约": "ka--he-tong-lv-yue",
    "KA-基础服务": "ka--ji-chu-fu-wu",
    "KA-委托项目招投标": "ka--wei-tuo-xiang-mu-zhao-tou-biao",
    "KA-开评标/结果": "ka--kai-ping-biao---jie-guo",
    "KA/云-企业计划": "ka--yun---qi-ye-ji-hua",
    "KA简易采购管理": "ka-jian-yi-cai-gou-guan-li",
    "S项目产品": "s-xiang-mu-chan-pin",
    "Z-ONE": "z-one",
    "npm 私库": "npm--si-ku",
    "pageoffice": "pageoffice",
    "token网关": "token-wang-guan",
    "万象工作台": "wan-xiang-gong-zuo-tai",
    "上海项目产品": "shang-hai-xiang-mu-chan-pin",
    "专家抽取引擎": "zhuan-jia-chou-qu-yin-qing",
    "专家抽取服务": "zhuan-jia-chou-qu-fu-wu",
    "专家管理系统": "zhuan-jia-guan-li-xi-tong",
    "业务代理mcp": "ye-wu-dai-li-mcp",
    "业务网关": "ye-wu-wang-guan",
    "中间件管理系统": "zhong-jian-jian-guan-li-xi-tong",
    "临时FAQ": "temp-faq",
    "乐采AGENT": "le-cai-agent",
    "乐采AI开发平台": "le-cai-ai-kai-fa-ping-tai",
    "乐采云专家抽取": "le-cai-yun-zhuan-jia-chou-qu",
    "乐采云公告中心": "le-cai-yun-gong-gao-zhong-xin",
    "乐采云共用组件": "le-cai-yun-gong-yong-zu-jian",
    "乐采云基础库管理": "le-cai-yun-ji-chu-ku-guan-li",
    "乐采云委托中心": "le-cai-yun-wei-tuo-zhong-xin",
    "乐采云小程序": "le-cai-yun-xiao-cheng-xu",
    "乐采云开评标中心": "le-cai-yun-kai-ping-biao-zhong-xin",
    "乐采云归档中心": "le-cai-yun-gui-dang-zhong-xin",
    "乐采云投标中心": "le-cai-yun-tou-biao-zhong-xin",
    "乐采云招标中心": "le-cai-yun-zhao-biao-zhong-xin",
    "乐采云结果中心": "le-cai-yun-jie-guo-zhong-xin",
    "乐采云计费中心": "le-cai-yun-ji-fei-zhong-xin",
    "乐采云诚信中心": "le-cai-yun-cheng-xin-zhong-xin",
    "乐采云运营提效平台": "le-cai-yun-yun-ying-ti-xiao-ping-tai",
    "乐采云项目中心": "le-cai-yun-xiang-mu-zhong-xin",
    "乐采云预警中心": "le-cai-yun-yu-jing-zhong-xin",
    "乐采对接": "le-cai-dui-jie",
    "乐采数据": "le-cai-shu-ju",
    "乐采配置": "le-cai-pei-zhi",
    "云随工作台": "yun-sui-gong-zuo-tai",
    "产品运营系统": "chan-pin-yun-ying-xi-tong",
    "产研大屏": "rd-dashboard",
    "人工智能应用": "ai-app",
    "代理机构管理系统": "dai-li-ji-gou-guan-li-xi-tong",
    "会议室管理": "meeting-room",
    "低代码搭建": "di-dai-ma-da-jian",
    "供应商业务全流程管理": "gong-ying-shang-ye-wu-quan-liu-cheng-guan-li",
    "供应商入驻": "gong-ying-shang-ru-zhu",
    "供应商分层": "gong-ying-shang-fen-ceng",
    "供应商管理系统": "gong-ying-shang-guan-li-xi-tong",
    "便民付": "public-service",
    "便民服务": "public-service",
    "保证金": "bao-zheng-jin",
    "保险保函": "bao-xian-bao-han",
    "免疫规划": "immunization",
    "免疫规划学习云": "immunization-learning",
    "免疫规划组": "immunization",
    "入学入托": "enrollment-check",
    "入学入托查验": "enrollment-check",
    "入学查验": "enrollment-check",
    "入驻管理系统": "ru-zhu-guan-li-xi-tong",
    "公务用车": "official-vehicle",
    "公告中心": "gong-gao-zhong-xin",
    "公款存放": "gong-kuan-cun-fang",
    "共享资源服务": "gong-xiang-zi-yuan-fu-wu",
    "关键词索引": "keyword-index",
    "其他行业采管": "qi-ta-hang-ye-cai-guan",
    "其他资金": "other-funds",
    "内容中心": "content-center",
    "军采合同": "jun-cai-he-tong",
    "军采履约": "jun-cai-lv-yue",
    "军采支付/结算": "jun-cai-zhi-fu---jie-suan",
    "军采评价": "jun-cai-ping-jia",
    "军采诚信": "jun-cai-cheng-xin",
    "军采预警": "jun-cai-yu-jing",
    "军队采购移动端": "jun-dui-cai-gou-yi-dong-duan",
    "冷链云": "cold-chain",
    "凭证中心": "voucher-center",
    "前台导购": "qian-tai-dao-gou",
    "前端物料系统": "qian-duan-wu-liao-xi-tong",
    "副食品项目": "fu-shi-pin-xiang-mu",
    "加班管理": "overtime",
    "加解密管理服务": "jia-jie-mi-guan-li-fu-wu",
    "医展馆": "yi-zhan-guan",
    "协议": "xie-yi",
    "单位与人员管理": "org-personnel",
    "卖场搭建（北极星）": "mai-chang-da-jian-(-bei-ji-xing-)",
    "原子搭建引擎": "yuan-zi-da-jian-yin-qing",
    "反拍": "fan-pai",
    "反爬服务": "fan-pa-fu-wu",
    "发票平台": "invoice-platform",
    "可观测系统": "ke-guan-ce-xi-tong",
    "合同": "he-tong",
    "合同中心": "contract-center",
    "合同管理": "he-tong-guan-li",
    "周报": "weekly",
    "品牌商业务全流程管理": "pin-pai-shang-ye-wu-quan-liu-cheng-guan-li",
    "品牌库": "pin-pai-ku",
    "商品助手": "shang-pin-zhu-shou",
    "商品审核": "shang-pin-shen-he",
    "商品巡检": "shang-pin-xun-jian",
    "商品标准体系": "shang-pin-biao-zhun-ti-xi",
    "商品管理": "shang-pin-guan-li",
    "商家数据产品": "shang-jia-shu-ju-chan-pin",
    "团购": "tuan-gou",
    "在线工作台": "zai-xian-gong-zuo-tai",
    "增信服务": "zeng-xin-fu-wu",
    "增值工具": "zeng-zhi-gong-ju",
    "备案": "bei-an",
    "夜餐管理": "meal-management",
    "天梯·自助接入服务": "tian-ti---zi-zhu-jie-ru-fu-wu",
    "天链·业务流程追踪": "tian-lian---ye-wu-liu-cheng-zhui-zong",
    "天门·通道网关服务": "tian-men---tong-dao-wang-guan-fu-wu",
    "夸克造物平台": "kua-ke-zao-wu-ping-tai",
    "委托": "wei-tuo",
    "孵化业务": "incubation",
    "安全资产管理": "an-quan-zi-chan-guan-li",
    "安全风险管理": "an-quan-feng-xian-guan-li",
    "客服机器人": "ke-fu-ji-qi-ren",
    "对账中心": "dui-zhang-zhong-xin",
    "小采DA": "xiao-cai-da",
    "小额工程(J)": "xiao-e-gong-cheng-(j)",
    "小额托收": "micro-collection",
    "履约": "lv-yue",
    "履约验收支付": "lv-yue-yan-shou-zhi-fu",
    "巡检管理": "inspection",
    "工作台": "gong-zuo-tai",
    "工作台/官网": "gong-zuo-tai---guan-wang",
    "工作台_官网": "workbench",
    "工作日服务": "gong-zuo-ri-fu-wu",
    "工作流服务": "gong-zuo-liu-fu-wu",
    "工作计划": "work-plan",
    "工单系统": "gong-dan-xi-tong",
    "工程管理": "engineering",
    "工资管理": "salary-management",
    "巨化乐采网": "ju-hua-le-cai-wang",
    "差异化配置能力": "cha-yi-hua-pei-zhi-neng-li",
    "帐户体系": "zhang-hu-ti-xi",
    "帮助中心": "bang-zhu-zhong-xin",
    "平台运维工具": "ping-tai-yun-wei-gong-ju",
    "平台运维需求导入": "ping-tai-yun-wei-xu-qiu-dao-ru",
    "应用市场": "app-market",
    "应用市场(浙里报)": "ying-yong-shi-chang-(-zhe-li-bao-)",
    "店铺助手": "dian-pu-zhu-shou",
    "开发者平台": "kai-fa-zhe-ping-tai",
    "开放平台": "open-platform",
    "开放平台(浙里报)": "kai-fang-ping-tai-(-zhe-li-bao-)",
    "开评标": "kai-ping-biao",
    "归档中心": "gui-dang-zhong-xin",
    "待办系统": "dai-ban-xi-tong",
    "微前端服务": "wei-qian-duan-fu-wu",
    "徽报账": "huibaozhang",
    "徽采云": "hui-cai-yun",
    "惠企利民": "enterprise-benefit",
    "成本平台": "cost-platform",
    "扁鹊·自助测试服务": "bian-que---zi-zhu-ce-shi-fu-wu",
    "找货助手": "zhao-huo-zhu-shou",
    "技术工单系统": "ji-shu-gong-dan-xi-tong",
    "投标": "tou-biao",
    "投诉质疑(行政裁决)": "tou-su-zhi-yi-(-xing-zheng-cai-jue-)",
    "拍卖": "pai-mai",
    "招标": "zhao-biao",
    "推荐": "tui-jian",
    "搜索": "sou-suo",
    "搜索中台": "sou-suo-zhong-tai",
    "搭建小程序": "da-jian-xiao-cheng-xu",
    "支付中心": "zhi-fu-zhong-xin",
    "收入管理": "revenue-management",
    "收费平台": "payment-platform",
    "政府投资": "gov-investment",
    "政策法规库": "zheng-ce-fa-gui-ku",
    "政采云APP": "zheng-cai-yun-app",
    "政采云军采版": "zheng-cai-yun-jun-cai-ban",
    "政采云商家版": "zheng-cai-yun-shang-jia-ban",
    "政采前端基础": "zheng-cai-qian-duan-ji-chu",
    "政采外部对接": "zheng-cai-wai-bu-dui-jie",
    "敏感词服务": "min-gan-ci-fu-wu",
    "数字人": "shu-zi-ren",
    "数字化支撑": "digital-support",
    "数字化支撑组": "digital-support",
    "数字化门诊": "digital-clinic",
    "数据助手": "shu-ju-zhu-shou",
    "数据大屏": "shu-ju-da-ping",
    "数据应用": "shu-ju-ying-yong",
    "数据智控": "data-control",
    "数据模型": "shu-ju-mo-xing",
    "数据监管": "data-supervision",
    "数据防泄漏服务": "shu-ju-fang-xie-lou-fu-wu",
    "数据集管理": "shu-ju-ji-guan-li",
    "数智一体化平台": "integration-platform",
    "数智算法": "shu-zhi-suan-fa",
    "数智财务AI+": "fin-ai",
    "数智财务AI＋": "fin-ai",
    "数智财务组": "fin-tech",
    "文件加解密": "wen-jian-jia-jie-mi",
    "文件回答-工具": "wen-jian-hui-da---gong-ju",
    "文件大纲摘要-工具": "wen-jian-da-gang-zhai-yao---gong-ju",
    "文件服务": "wen-jian-fu-wu",
    "文档服务": "wen-dang-fu-wu",
    "日志服务": "ri-zhi-fu-wu",
    "智慧门诊": "smart-clinic",
    "智慧问答-工具": "zhi-hui-wen-da---gong-ju",
    "智算管理系统": "zhi-suan-guan-li-xi-tong",
    "智能交易": "zhi-neng-jiao-yi",
    "智能体前台": "zhi-neng-ti-qian-tai",
    "智能体开发系统": "zhi-neng-ti-kai-fa-xi-tong",
    "智能催种": "smart-reminder",
    "智能合同管理-插件": "zhi-neng-he-tong-guan-li---cha-jian",
    "智能围串标识别-工具": "zhi-neng-wei-chuan-biao-shi-bie---gong-ju",
    "智能围串标识别-插件": "zhi-neng-wei-chuan-biao-shi-bie---cha-jian",
    "智能引擎": "zhi-neng-yin-qing",
    "智能投诉质疑处理-工具": "zhi-neng-tou-su-zhi-yi-chu-li---gong-ju",
    "智能招标文件检测-工具": "zhi-neng-zhao-biao-wen-jian-jian-ce---gong-ju",
    "智能招标文件检测-插件": "zhi-neng-zhao-biao-wen-jian-jian-ce---cha-jian",
    "智能招标文件编制-工具": "zhi-neng-zhao-biao-wen-jian-bian-zhi---gong-ju",
    "智能文件推荐-插件": "zhi-neng-wen-jian-tui-jian---cha-jian",
    "智能比价-插件": "zhi-neng-bi-jia---cha-jian",
    "智能监管": "zhi-neng-jian-guan",
    "智能竞价单提取-插件": "zhi-neng-jing-jia-dan-ti-qu---cha-jian",
    "智能辅助评标-工具": "zhi-neng-fu-zhu-ping-biao---gong-ju",
    "智能辅助评标-插件": "zhi-neng-fu-zhu-ping-biao---cha-jian",
    "智能采购助手": "zhi-neng-cai-gou-zhu-shou",
    "智能采购文件提取-插件": "zhi-neng-cai-gou-wen-jian-ti-qu---cha-jian",
    "月报": "monthly",
    "服务市场": "fu-wu-shi-chang",
    "权限管理系统": "quan-xian-guan-li-xi-tong",
    "标的库": "biao-di-ku",
    "标讯平台": "biao-xun-ping-tai",
    "核算归档": "accounting-archive",
    "榫卯": "sun-mao",
    "榫卯搭建APP": "sun-mao-da-jian-app",
    "榫卯搭建H5": "sun-mao-da-jian-h5",
    "榫卯搭建小程序": "sun-mao-da-jian-xiao-cheng-xu",
    "模板服务": "mu-ban-fu-wu",
    "模版中心": "template-center",
    "比价AGENT": "bi-jia-agent",
    "求购征资": "qiu-gou-zheng-zi",
    "流程管理": "workflow",
    "流转日志": "liu-zhuan-ri-zhi",
    "流量调控": "liu-liang-tiao-kong",
    "浑仪": "hun-yi",
    "浙里办": "zheliban",
    "浙里报": "zhelibao",
    "浙里接种": "zheli-vaccination",
    "浙里接种管理端": "zheli-vaccine-admin",
    "浙里接种管理端（双钉）": "zhe-li-jie-zhong-guan-li-duan-(-shuang-ding-)",
    "消息中心": "message-center",
    "消息平台": "message-platform",
    "消息通知系统": "xiao-xi-tong-zhi-xi-tong",
    "溯采PLUS会员": "su-cai-plus-hui-yuan",
    "溯采SaaS": "su-cai-saas",
    "溯采交易管理": "su-cai-jiao-yi-guan-li",
    "溯采会员": "su-cai-hui-yuan",
    "溯采供应商管理": "su-cai-gong-ying-shang-guan-li",
    "溯采商品管理": "su-cai-shang-pin-guan-li",
    "溯采商城前台": "su-cai-shang-cheng-qian-tai",
    "溯采支付结算": "su-cai-zhi-fu-jie-suan",
    "溯采用户管理": "su-cai-yong-hu-guan-li",
    "溯采营销管理": "su-cai-ying-xiao-guan-li",
    "溯采询价管理": "su-cai-xun-jia-guan-li",
    "灵龙客户端": "ling-long-ke-hu-duan",
    "热线工作台": "re-xian-gong-zuo-tai",
    "爬虫网关服务": "pa-chong-wang-guan-fu-wu",
    "特殊事项": "te-shu-shi-xiang",
    "生态对接": "eco-integration",
    "用户&工作台": "yong-hu-&-gong-zuo-tai",
    "用户体系": "user-system",
    "用户管理系统": "yong-hu-guan-li-xi-tong",
    "电子卖场-通用组件": "dian-zi-mai-chang---tong-yong-zu-jian",
    "电子档案": "e-archive",
    "电子档案组": "e-archive",
    "畅写": "chang-xie",
    "疫苗数仓": "vaccine-dataware",
    "疫苗通用": "vaccine-common",
    "疫苗馆": "vaccine-hall",
    "百搭": "baida",
    "直属": "direct",
    "直购": "zhi-gou",
    "直购AGENT": "zhi-gou-agent",
    "知识中台": "zhi-shi-zhong-tai",
    "知识库管理": "zhi-shi-ku-guan-li",
    "知识管理手册视频制作": "zhi-shi-guan-li-shou-ce-shi-pin-zhi-zuo",
    "短链服务": "duan-lian-fu-wu",
    "研发平台元数据": "yan-fa-ping-tai-yuan-shu-ju",
    "研发平台用户中心（IDaas）": "yan-fa-ping-tai-yong-hu-zhong-xin-(idaas)",
    "神笔": "shen-bi",
    "票据管理": "invoice-management",
    "竞价": "jing-jia",
    "竞价AGENT": "jing-jia-agent",
    "管物SaaS": "asset-saas",
    "箪食": "dan-shi",
    "类目标准体系": "lei-mu-biao-zhun-ti-xi",
    "结果": "jie-guo",
    "结算/支付单": "jie-suan---zhi-fu-dan",
    "结算中心": "settlement-center",
    "结算平台": "settlement-platform",
    "统一发布系统": "tong-yi-fa-bu-xi-tong",
    "绩效管理": "performance",
    "绿色建材项目管理": "lv-se-jian-cai-xiang-mu-guan-li",
    "绿色建材馆": "lv-se-jian-cai-guan",
    "网站群": "wang-zhan-qun",
    "网络防火墙（WAF）": "wang-luo-fang-huo-qiang-(waf)",
    "考勤管理": "attendance",
    "考核总结": "assessment",
    "节点驱动": "jie-dian-qu-dong",
    "营收平台": "revenue-platform",
    "营销能力": "ying-xiao-neng-li",
    "融资贷款": "rong-zi-dai-kuan",
    "行采小型化": "xing-cai-xiao-xing-hua",
    "表单搭建（无相）": "biao-dan-da-jian-(-wu-xiang-)",
    "订单": "ding-dan",
    "订购体系": "ding-gou-ti-xi",
    "设计支持": "she-ji-zhi-chi",
    "评测任务管理": "ping-ce-ren-wu-guan-li",
    "诚信中心": "cheng-xin-zhong-xin",
    "财政指标管理": "fiscal-indicator",
    "账户中心": "zhang-hu-zhong-xin",
    "质量管理系统": "zhi-liang-guan-li-xi-tong",
    "费控管理": "cost-control",
    "资产管理": "asset-management",
    "资产管理平台": "asset-platform",
    "资金助手": "zi-jin-zhu-shou",
    "超职购": "chao-zhi-gou",
    "车辆控购": "che-liang-kong-gou",
    "车辆管理": "vehicle-management",
    "辅助功能": "auxiliary",
    "运营后台": "ops-console",
    "进口产品核准": "jin-kou-chan-pin-he-zhun",
    "进货助手": "jin-huo-zhu-shou",
    "通信服务": "tong-xin-fu-wu",
    "通用内容中心": "tong-yong-nei-rong-zhong-xin",
    "配置中心": "pei-zhi-zhong-xin",
    "采/非采场景": "purchase-scene",
    "采_非采场景": "purchase-scene",
    "采云学院": "cai-yun-xue-yuan",
    "采云惠": "cai-yun-hui",
    "采小蜜挂件": "cai-xiao-mi-gua-jian",
    "采购人管理系统": "cai-gou-ren-guan-li-xi-tong",
    "采购方案": "cai-gou-fang-an",
    "采购目录": "cai-gou-mu-lu",
    "采购管理": "procurement",
    "采购联合会、红黑榜": "cai-gou-lian-he-hui-、-hong-hei-bang",
    "采购计划": "cai-gou-ji-hua",
    "采购需求标准": "cai-gou-xu-qiu-biao-zhun",
    "采购项目": "cai-gou-xiang-mu",
    "金融中台": "jin-rong-zhong-tai",
    "金融助手": "jin-rong-zhu-shou",
    "错别字检查修正-工具": "cuo-bie-zi-jian-cha-xiu-zheng---gong-ju",
    "集成平台": "ji-cheng-ping-tai",
    "需求管理": "xu-qiu-guan-li",
    "青鸾·数据交换服务": "qing-luan---shu-ju-jiao-huan-fu-wu",
    "音视频基建": "yin-shi-pin-ji-jian",
    "项目": "xiang-mu",
    "项目监管": "xiang-mu-jian-guan",
    "项目管理": "project-management",
    "项目管理系统": "xiang-mu-guan-li-xi-tong",
    "项目采购基建": "xiang-mu-cai-gou-ji-jian",
    "项目采购长链接": "xiang-mu-cai-gou-zhang-lian-jie",
    "预算中心": "budget-center",
    "预算管理": "yu-suan-guan-li",
    "预警中心": "yu-jing-zhong-xin",
    "预防接种": "vaccination",
    "风控服务": "feng-kong-fu-wu",
    "高校采管": "gao-xiao-cai-guan",
    "高速公路": "gao-su-gong-lu",
    "鲁班": "lu-ban",
    "鸿蒙适配": "hong-meng-shi-pei",
}
PATH_TO_SUBMODULE = {v: k for k, v in SUBMODULE_TO_PATH.items()}

# 其他目录映射
OTHER_DIR_MAP = {
    "周报": "weekly",
    "月报": "monthly",
    "FAQ知识库": None,  # 删除，与 faq/ 冗余
    "关键词索引": "keyword-index",
}

# 需要排除的旧目录（会被删除）
DEPRECATED_DIRS = ["FAQ知识库"]


def get_dept_path(dept_name: str) -> str:
    """中文部门名 → 英文路径名（数据库优先 → 代码映射 → 拼音兜底）"""
    # 1. 数据库优先：dir_name 可通过 Web 管理界面修改，无需改代码
    try:
        from .db_repo import DBRepository
        repo = DBRepository()
        row = repo._execute_one(
            "SELECT dir_name FROM departments WHERE name = ? AND dir_name IS NOT NULL AND dir_name != ''",
            (dept_name,)
        )
        if row and row.get("dir_name"):
            return row["dir_name"]
    except Exception:
        pass

    # 2. 代码映射：兜底保障
    if dept_name in DEPT_TO_PATH:
        return DEPT_TO_PATH[dept_name]

    # 3. 拼音兜底：确保新部门不会产生中文路径
    try:
        from pypinyin import lazy_pinyin
        return "-".join(lazy_pinyin(dept_name))
    except ImportError:
        return dept_name


def get_dept_name(dept_path: str) -> str:
    """英文路径名 → 中文部门名"""
    return PATH_TO_DEPT.get(dept_path, dept_path)


def get_submodule_path(sub_name: str) -> str:
    """中文子模块名 → 英文路径名（优先数据库，其次映射表，最后拼音兜底）"""
    # 1. 数据库查询（modules.dir_name）
    try:
        from .db_repo import DBRepository
        repo = DBRepository()
        row = repo._execute_one("SELECT dir_name FROM modules WHERE name = ? AND dir_name IS NOT NULL", (sub_name,))
        if row and row.get("dir_name"):
            return row["dir_name"]
    except Exception:
        pass

    # 2. 映射表
    if sub_name in SUBMODULE_TO_PATH:
        return SUBMODULE_TO_PATH[sub_name]

    # 3. 拼音兜底
    try:
        from pypinyin import lazy_pinyin
        return "-".join(lazy_pinyin(sub_name))
    except ImportError:
        return sub_name


def get_submodule_name(sub_path: str) -> str:
    """英文路径名 → 中文子模块名"""
    return PATH_TO_SUBMODULE.get(sub_path, sub_path)